apiVersion: v1
kind: Service
metadata:
  name: {{ include "car-overlay.fullname" . }}-back
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
  selector:
    {{- include "car-overlay.selectorLabels" . | nindent 4 }}
    component: back
